### PR TITLE
Angular Material 19 compatibility

### PR DESCRIPTION
**Pull request by imario42**
That is a first try to make that library Angular Material 19 compatible.
It compiles and the examples do not look bad to me.

### CODE REVIEW

**Comment by mspeak** [comment]
@GNURub Any change for a Material v19 publish?

**Comment by imario42** [comment]
@mspeak Maybe you can test my bundle in the meantime?
https://www.npmjs.com/package/@imario42/datetime-picker

**Comment by mspeak** [comment]
@imario42 Will do, just need datetime picker, thanks

**Comment by Sergiobop** [comment]
Hi @imario42 , how can i test it with the moment adapter?

I tried your version and ngxmc/moment-adapter (^19.0.0):

Could not resolve "@ngxmc/datetime-picker"

    node_modules/@ngxmc/moment-adapter/fesm2022/ngxmc-moment-adapter.mjs:5:56:
      5 │ import { NgxMatDateAdapter, NGX_MAT_DATE_FORMATS } from '@ngxmc/datetime-picker';

**Pull request merged**
